# site settings
title: Cryptoeconomics.hub
subtitle: null
email: cryptoeconomics.hub@gmail.com
description: Cryptoeconomics is what makes blockchain technology exiting. It is about designing incentives to lead people's behaviour into a certain direction without forcing anyone. It makes use of cryptography, game theory and mechanism design to align the incentives of the participants of an economic network to get to a desirable outcome.
baseurl: # the subpath of your site, e.g. /blog
url: "https://cryptoeconomics-hub.github.io" # the base hostname & protocol for your site
author:
venue: International Lab
street_address: Calle Bailen 41
city: Madrid
state:
zip_code: 28013
country: Spain
phone:
telegram: https://t.me/cryptoeconomics

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:
telegram_url:
discord_url:
youtube_url:
medium_url:

# build settings
markdown: kramdown

sass:
  style: compressed
