# site settings
title: Cryptoeconomics.hub
subtitle: The Power and Fear of Incentives
email: cryptoeconomics.hub@gmail.com
description: Cryptoeconomics is what makes blockchain technology so exiting. It is about designing incentives to lead people's behaviour into a certain direction without forcing anyone. It is about cryptography, game theory, mechanism design, behavioural economics and so much more.
baseurl: # the subpath of your site, e.g. /blog
url: "https://cryptoeconomics-hub.github.io" # the base hostname & protocol for your site
author:
street_address:
city:
state:
zip_code:
country: Spain
phone:

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/cryptoeconomics-hub
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:
telegram_url: https://t.me/cryptoeconomics
discord_url: https://discord.gg/G9QbbC

# build settings
markdown: kramdown

sass:
  style: compressed
