# site settings
title: Cryptoeconomics.hub
subtitle: 
email: cryptoeconomics.hub@gmail.com
description: Cryptoeconomics is complex, but this exactly makes it so attractive, not mentioning its potential, which is enormous and still uncovered. The idea of this Meetup is to present this new research topic by inviting speakers and having open discussions.
baseurl: "/cryptoeconomics-hub.github.io" # the subpath of your site, e.g. /blog
url: "https://cryptoeconomics-hub.github.io" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
